[package]
name = "bevy-learn"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy_obj = "0.15.0"
simdnoise = "3.1.6"
avian3d = "0.2.0"
smooth-bevy-cameras = "0.13.0"
bevy-tnua = "0.21"
bevy-tnua-avian3d = "0.2"
bevy-tnua-physics-integration-layer = "0.5.0"
rand = "0.8.5"

