[package]
name = "bevy_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
simdnoise = "3.1.6"
smooth-bevy-cameras = "0.13.0"
bevy_rapier3d = "0.28.0"
bevy-tnua = "0.21"
bevy-tnua-physics-integration-layer = "0.5.0"
bevy-tnua-rapier3d = "0.9.0"
rand = "0.8.5"
