[package]
name = "bevy_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
simdnoise = "3.1.6"
smooth-bevy-cameras = "0.13.0"
rand = "0.8.5"
bevy_rapier3d = { version = "0.28", features = ["parallel", "simd-stable"] }
